# Generated by Django 5.1.5 on 2025-01-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_theme_name_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_home",
            field=models.BooleanField(default=False),
        ),
    ]
