# Generated by Django 5.1.5 on 2025-01-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_social_login",
                    models.BooleanField(
                        default=True, verbose_name="Autoriser la connexion sociale"
                    ),
                ),
                (
                    "login_attempts",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Nombre de tentatives de connexion"
                    ),
                ),
                (
                    "lockout_time",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Temps de verrouillage (minutes)"
                    ),
                ),
                (
                    "remember_me",
                    models.BooleanField(
                        default=True, verbose_name="Activer 'Se souvenir de moi'"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de connexion",
                "verbose_name_plural": "Configurations de connexion",
            },
        ),
        migrations.CreateModel(
            name="PageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("logo_max_width", models.CharField(default="200px", max_length=50)),
                (
                    "submit_button_text",
                    models.CharField(default="Soumettre", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=True, verbose_name="Exiger la vérification par email"
                    ),
                ),
                (
                    "minimum_password_length",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Longueur minimale du mot de passe"
                    ),
                ),
                (
                    "require_special_char",
                    models.BooleanField(
                        default=True, verbose_name="Exiger un caractère spécial"
                    ),
                ),
                (
                    "require_uppercase",
                    models.BooleanField(
                        default=True, verbose_name="Exiger une majuscule"
                    ),
                ),
                (
                    "require_number",
                    models.BooleanField(default=True, verbose_name="Exiger un chiffre"),
                ),
                (
                    "terms_and_conditions_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="URL des conditions d'utilisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration d'inscription",
                "verbose_name_plural": "Configurations d'inscription",
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=100, verbose_name="Nom du site"),
                ),
                (
                    "site_description",
                    models.TextField(verbose_name="Description du site"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                ("address", models.TextField(verbose_name="Adresse")),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="URL Facebook"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="URL Twitter"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL Instagram"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configurations du site",
            },
        ),
    ]
